[package]
name = "tetroid"
version = "0.1.0"
authors = ["Tubbles <jae91m@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#tetra = "0.6"
sdl2 = "0.34"

